name: Cron Job

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  run-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: call the vercel cron job
        uses: curl -X POST http://http://localhost:3000/api/cron-job

      